version: "3"

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    restart: unless-stopped
    ports:
      - 5434:5432/tcp
    environment:
      POSTGRES_DB: code_challenge_development
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: code_challenge
    networks:
      - my_red
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    stdin_open: true
    tty: true
  code_challenge:
    restart: unless-stopped
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p $PORT -b '0.0.0.0'"
    volumes:
      - ~/.ssh:/root/.ssh-local:ro
      - .:/myapp
    ports:
      - "80:80"
    environment:
      BACKEND_DATABASE: code_challenge_development
      BACKEND_DATABASE_USER: postgres
      BACKEND_DATABASE_PASSWORD: code_challenge
      BACKEND_DATABASE_HOST: db
      BACKEND_DATABASE_PORT: 5432
      RAILS_ENV: development
      PORT: 80
    networks:
      - my_red
    depends_on:
      - db
networks:
  default:
    external:
      name: nest-net
  my_red:
    # Use a custom driver
    driver: bridge
